-- MySQL Script generated by MySQL Workbench
-- vie 21 ago 2015 18:22:17 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ExpertSystemAutismDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ExpertSystemAutismDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExpertSystemAutismDB` DEFAULT CHARACTER SET utf8 ;
USE `ExpertSystemAutismDB` ;

-- -----------------------------------------------------
-- Table `ExpertSystemAutismDB`.`Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpertSystemAutismDB`.`Results` (
  `threatment_id` INT(11) NOT NULL,
  `threatment_description` VARCHAR(250) NOT NULL,
  `diagnosis_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`threatment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpertSystemAutismDB`.`Diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpertSystemAutismDB`.`Diagnosis` (
  `diagnosis_id` INT(11) NOT NULL AUTO_INCREMENT,
  `diagnosis_threatment` INT(11) NULL DEFAULT NULL,
  `diagnosis_result` VARCHAR(25) NULL DEFAULT NULL,
  `threatment_id` INT(11) NOT NULL,
  `updated_at` VARCHAR(30) NULL DEFAULT NULL,
  `deleted_at` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`diagnosis_id`),
  INDEX `fk_Diagnosis_Results1_idx` (`threatment_id` ASC),
  CONSTRAINT `fk_Diagnosis_Results1`
    FOREIGN KEY (`threatment_id`)
    REFERENCES `ExpertSystemAutismDB`.`Results` (`threatment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpertSystemAutismDB`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpertSystemAutismDB`.`Login` (
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ExpertSystemAutismDB`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpertSystemAutismDB`.`Patient` (
  `patient_id` INT(11) NOT NULL,
  `patient_historialnumber` INT(10) NULL DEFAULT NULL,
  `patient_name` VARCHAR(100) NOT NULL,
  `patient_address` VARCHAR(100) NOT NULL,
  `patient_phonenumber` VARCHAR(20) NOT NULL,
  `diagnosis_id` INT(11) NULL DEFAULT NULL,
  `updated_at` VARCHAR(30) NULL DEFAULT NULL,
  `deleted_at` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`patient_id`),
  INDEX `fk_Patient_Diagnosis_idx` (`diagnosis_id` ASC),
  CONSTRAINT `fk_Patient_Diagnosis`
    FOREIGN KEY (`diagnosis_id`)
    REFERENCES `ExpertSystemAutismDB`.`Diagnosis` (`diagnosis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
