/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AESViews;

import java.beans.PropertyVetoException;

/**
 *
 * @author otamega
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        //this.setExtendedState(NewJFramePrincipal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuRegisters = new javax.swing.JMenu();
        jMenuItemNewPatient = new javax.swing.JMenuItem();
        jMenuItemNewUser = new javax.swing.JMenuItem();
        jMenuItemViewPatients = new javax.swing.JMenuItem();
        jMenuItemViewUsers = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESA: Sistema experto para el diagnóstico de autismo");

        MenuRegisters.setMnemonic('f');
        MenuRegisters.setText("Registro");

        jMenuItemNewPatient.setMnemonic('o');
        jMenuItemNewPatient.setText("Registrar nuevo paciente");
        jMenuItemNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewPatientActionPerformed(evt);
            }
        });
        MenuRegisters.add(jMenuItemNewPatient);

        jMenuItemNewUser.setMnemonic('s');
        jMenuItemNewUser.setText("Registrar nuevo usuario");
        jMenuItemNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemNewUserMouseClicked(evt);
            }
        });
        jMenuItemNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewUserActionPerformed(evt);
            }
        });
        MenuRegisters.add(jMenuItemNewUser);

        jMenuItemViewPatients.setText("Ver pacientes");
        jMenuItemViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewPatientsActionPerformed(evt);
            }
        });
        MenuRegisters.add(jMenuItemViewPatients);

        jMenuItemViewUsers.setText("Ver usuarios");
        jMenuItemViewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemViewUsersMouseClicked(evt);
            }
        });
        jMenuItemViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewUsersActionPerformed(evt);
            }
        });
        MenuRegisters.add(jMenuItemViewUsers);

        menuBar.add(MenuRegisters);

        editMenu.setMnemonic('e');
        editMenu.setText("Diagnóstico");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Iniciar diagnóstico");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Ver diagnósticos");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        JInternalFrameStartDiagnosis FrameStartDiagnosis = new JInternalFrameStartDiagnosis();
        desktopPane.add(FrameStartDiagnosis);
        FrameStartDiagnosis.show();
        FrameStartDiagnosis.setMaximizable(true);
        FrameStartDiagnosis.setIconifiable(true);
        FrameStartDiagnosis.setResizable(false);
        FrameStartDiagnosis.setClosable(true);
        FrameStartDiagnosis.toFront();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMenuItemNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewPatientActionPerformed
        JInternalFrameNewPatient FrameNewPatient = new JInternalFrameNewPatient();
        desktopPane.add(FrameNewPatient);
        FrameNewPatient.show();
        FrameNewPatient.setMaximizable(true);
        FrameNewPatient.setIconifiable(true);
        FrameNewPatient.setResizable(false);
        FrameNewPatient.setClosable(true);
        FrameNewPatient.toFront();
    }//GEN-LAST:event_jMenuItemNewPatientActionPerformed

    private void jMenuItemViewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemViewUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemViewUsersMouseClicked

    private void jMenuItemNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemNewUserMouseClicked
  
    }//GEN-LAST:event_jMenuItemNewUserMouseClicked

    private void jMenuItemNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewUserActionPerformed
        JInternalFrameNewUser FrameNewUser = new JInternalFrameNewUser();
        desktopPane.add(FrameNewUser);
        FrameNewUser.show();
        FrameNewUser.setMaximizable(true);
        FrameNewUser.setIconifiable(true);
        FrameNewUser.setResizable(false);
        FrameNewUser.setClosable(true);
        FrameNewUser.toFront();
    }//GEN-LAST:event_jMenuItemNewUserActionPerformed

    private void jMenuItemViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewPatientsActionPerformed
        JInternalFrameViewPatient FrameViewPatient = new JInternalFrameViewPatient();
        desktopPane.add(FrameViewPatient);
        FrameViewPatient.show();
        FrameViewPatient.setMaximizable(true);
        FrameViewPatient.setIconifiable(true);
        FrameViewPatient.setResizable(false);
        FrameViewPatient.setClosable(true);
        FrameViewPatient.toFront();
    }//GEN-LAST:event_jMenuItemViewPatientsActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        JInternalFrameViewDiagnosis FrameViewDiagnosis = new JInternalFrameViewDiagnosis();
        desktopPane.add(FrameViewDiagnosis);
        FrameViewDiagnosis.show();
        FrameViewDiagnosis.setMaximizable(true);
        FrameViewDiagnosis.setIconifiable(true);
        FrameViewDiagnosis.setResizable(false);
        FrameViewDiagnosis.setClosable(true);
        FrameViewDiagnosis.toFront();
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void jMenuItemViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewUsersActionPerformed
         JInternalFrameViewUser FrameViewUser = new JInternalFrameViewUser();
        desktopPane.add(FrameViewUser);
        FrameViewUser.show();
        FrameViewUser.setMaximizable(true);
        FrameViewUser.setIconifiable(true);
        FrameViewUser.setResizable(false);
        FrameViewUser.setClosable(true);
        FrameViewUser.toFront();
    }//GEN-LAST:event_jMenuItemViewUsersActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuRegisters;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemNewPatient;
    private javax.swing.JMenuItem jMenuItemNewUser;
    private javax.swing.JMenuItem jMenuItemViewPatients;
    private javax.swing.JMenuItem jMenuItemViewUsers;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
