/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AESViews;

import AESDAO.PatientDAO;
import AESData.PatientData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author otamega
 */
public class JInternalFrameViewPatient extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameViewPatient
     */
    private String deleted = "";
    
    public JInternalFrameViewPatient() {
        initComponents();
        dataLoad("");
    }
    
    private void dataLoad(String search) {

        try {
            DefaultTableModel model;
            PatientDAO patientDAO = new PatientDAO();
            model = patientDAO.dataLoad(search);

            jTablePatient.setModel(model);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    private void clean() {
        jTextFieldSearch.setText("");
        jTextFieldPatientAddress.setText("");
        jTextFieldPatientHistorialNumber.setText("");
        jTextFieldPatientId.setText("");
        jTextFieldPatientName.setText("");
        jTextFieldPatientPhoneNumber.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelViewPatient = new javax.swing.JPanel();
        jLabelViewPatientTitle = new javax.swing.JLabel();
        jPanelOptionFrame = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatient = new javax.swing.JTable();
        jPanelData = new javax.swing.JPanel();
        jLabelPatientName = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldPatientName = new javax.swing.JTextField();
        jTextFieldPatientAddress = new javax.swing.JTextField();
        jLabelPatientId = new javax.swing.JLabel();
        jTextFieldPatientId = new javax.swing.JTextField();
        jLabelPatientPhoneNumber = new javax.swing.JLabel();
        jTextFieldPatientPhoneNumber = new javax.swing.JTextField();
        jButtonReportView = new javax.swing.JButton();
        jLabelPatientHistorialNumber = new javax.swing.JLabel();
        jTextFieldPatientHistorialNumber = new javax.swing.JTextField();

        setTitle("Consulta de pacientes registrados");

        jLabelViewPatientTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelViewPatientTitle.setText("Pacientes registrados");

        jPanelOptionFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Marco de opciones"));

        jButtonSearch.setText("Buscar");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Editar");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refrescar");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOptionFrameLayout = new javax.swing.GroupLayout(jPanelOptionFrame);
        jPanelOptionFrame.setLayout(jPanelOptionFrameLayout);
        jPanelOptionFrameLayout.setHorizontalGroup(
            jPanelOptionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDelete)
                .addContainerGap())
        );
        jPanelOptionFrameLayout.setVerticalGroup(
            jPanelOptionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePatient);

        jPanelData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabelPatientName.setText("Nombre:");

        jLabelAddress.setText("Dirección:");

        jLabelPatientId.setText("Identidad:");

        jLabelPatientPhoneNumber.setText("Teléfono:");

        jButtonReportView.setText("Ver reporte");

        jLabelPatientHistorialNumber.setText("Nro historia");

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDataLayout.createSequentialGroup()
                        .addComponent(jLabelPatientId)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDataLayout.createSequentialGroup()
                        .addComponent(jLabelPatientHistorialNumber)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldPatientHistorialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDataLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelPatientName)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPatientPhoneNumber)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldPatientPhoneNumber))
                    .addGroup(jPanelDataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAddress)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReportView)))
                .addContainerGap())
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPatientId)
                        .addComponent(jTextFieldPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPatientPhoneNumber)
                        .addComponent(jTextFieldPatientPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPatientName)
                        .addComponent(jTextFieldPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAddress)
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReportView))
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPatientHistorialNumber)
                        .addComponent(jTextFieldPatientHistorialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelViewPatientLayout = new javax.swing.GroupLayout(jPanelViewPatient);
        jPanelViewPatient.setLayout(jPanelViewPatientLayout);
        jPanelViewPatientLayout.setHorizontalGroup(
            jPanelViewPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelViewPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOptionFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelViewPatientLayout.createSequentialGroup()
                        .addComponent(jLabelViewPatientTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelViewPatientLayout.setVerticalGroup(
            jPanelViewPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewPatientLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelViewPatientTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOptionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePatientMouseClicked
        int row = jTablePatient.rowAtPoint(evt.getPoint());
        jTextFieldPatientId.setText(jTablePatient.getValueAt(row, 0).toString());
        jTextFieldPatientHistorialNumber.setText(jTablePatient.getValueAt(row, 1).toString());
        jTextFieldPatientName.setText(jTablePatient.getValueAt(row, 2).toString());
        jTextFieldPatientPhoneNumber.setText(jTablePatient.getValueAt(row, 3).toString());
        jTextFieldPatientAddress.setText(jTablePatient.getValueAt(row, 4).toString());
        deleted = (jTablePatient.getValueAt(row, 6).toString());
        System.out.print(deleted);
    }//GEN-LAST:event_jTablePatientMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        PatientData patientData = new PatientData();
        PatientDAO patientDAO = new PatientDAO();
        
        patientData.setPatientId(Integer.parseInt(jTextFieldPatientId.getText()));
        patientData.setPatientName(jTextFieldPatientName.getText());
        patientData.setPatientAddress(jTextFieldPatientAddress.getText());
        patientData.setPatientPhoneNumber(jTextFieldPatientPhoneNumber.getText());
        patientData.setHistorialNumber(Integer.parseInt(jTextFieldPatientHistorialNumber.getText()));
        
        patientDAO.update(patientData);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        PatientData patientData = new PatientData();
        PatientDAO patientDAO = new PatientDAO();
        
        int j = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea eliminar lo que ha seleccionado en la tabla?", "¡Alerta!", JOptionPane.OK_CANCEL_OPTION);
        if ((j) == JOptionPane.OK_OPTION) {

            if ((deleted.length()) >= 2) {

                JOptionPane.showMessageDialog(rootPane, "Ya este paciente fue eliminado anteriormente");
                return;

            }

            patientData.setPatientId(Integer.parseInt(jTextFieldPatientId.getText()));
            patientDAO.delete(patientData);

            JOptionPane.showMessageDialog(rootPane, "Paciente eliminado de la lista exitosamente");
            jTextFieldSearch.setText("");
            dataLoad(jTextFieldSearch.getText());

        }

        if ((j) == JOptionPane.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "No se ha eliminado nada");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        dataLoad(jTextFieldSearch.getText());
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        clean();
        dataLoad("");
    }//GEN-LAST:event_jButtonRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonReportView;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelPatientHistorialNumber;
    private javax.swing.JLabel jLabelPatientId;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelPatientPhoneNumber;
    private javax.swing.JLabel jLabelViewPatientTitle;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelOptionFrame;
    private javax.swing.JPanel jPanelViewPatient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePatient;
    private javax.swing.JTextField jTextFieldPatientAddress;
    private javax.swing.JTextField jTextFieldPatientHistorialNumber;
    private javax.swing.JTextField jTextFieldPatientId;
    private javax.swing.JTextField jTextFieldPatientName;
    private javax.swing.JTextField jTextFieldPatientPhoneNumber;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
