/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AESViews;

import AESDAO.DiagnosisDAO;
import AESDAO.PatientDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author otamega
 */
public class JInternalFramePatientDiagnosis extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFramePatientDiagnosis
     */
    private String diagnosis_id = "";
    
    public JInternalFramePatientDiagnosis() {
        initComponents();
        this.setTitle("Consulta general paciente/diagnóstico");
        dataLoadPatient("");
    }

    private void dataLoadPatient(String search) {

        try {
            DefaultTableModel model;
            PatientDAO patientDAO = new PatientDAO();
            model = patientDAO.dataLoad(search);

            jTablePatient.setModel(model);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    private void dataLoadDiagnosis(String search) {

        try {
            DefaultTableModel model;
            DiagnosisDAO diagnosisDAO = new DiagnosisDAO();
            model = diagnosisDAO.showDiagnosis(search);

            jTableDiagnosis.setModel(model);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPatientDiagnosis = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelPatient = new javax.swing.JPanel();
        jLabelPatientSearch = new javax.swing.JLabel();
        jTextFieldPatientSearch = new javax.swing.JTextField();
        jButtonPatientSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatient = new javax.swing.JTable();
        jPanelDiagnosis = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDiagnosis = new javax.swing.JTable();

        jLabelTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelTitle.setText("Consulta de pacientes y diagnósticos");

        jPanelPatient.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de pacientes"));

        jLabelPatientSearch.setText("Buscar:");

        jButtonPatientSearch.setText("Buscar");
        jButtonPatientSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientSearchActionPerformed(evt);
            }
        });

        jTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePatient);

        javax.swing.GroupLayout jPanelPatientLayout = new javax.swing.GroupLayout(jPanelPatient);
        jPanelPatient.setLayout(jPanelPatientLayout);
        jPanelPatientLayout.setHorizontalGroup(
            jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelPatientLayout.createSequentialGroup()
                        .addComponent(jLabelPatientSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPatientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPatientSearch)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPatientLayout.setVerticalGroup(
            jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPatientSearch)
                    .addComponent(jTextFieldPatientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPatientSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDiagnosis.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnósticos encontrados"));

        jTableDiagnosis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDiagnosis.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableDiagnosisComponentAdded(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDiagnosis);

        javax.swing.GroupLayout jPanelDiagnosisLayout = new javax.swing.GroupLayout(jPanelDiagnosis);
        jPanelDiagnosis.setLayout(jPanelDiagnosisLayout);
        jPanelDiagnosisLayout.setHorizontalGroup(
            jPanelDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiagnosisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDiagnosisLayout.setVerticalGroup(
            jPanelDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiagnosisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPatientDiagnosisLayout = new javax.swing.GroupLayout(jPanelPatientDiagnosis);
        jPanelPatientDiagnosis.setLayout(jPanelPatientDiagnosisLayout);
        jPanelPatientDiagnosisLayout.setHorizontalGroup(
            jPanelPatientDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientDiagnosisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPatientDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPatientDiagnosisLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPatientDiagnosisLayout.createSequentialGroup()
                        .addGroup(jPanelPatientDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelDiagnosis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
        );
        jPanelPatientDiagnosisLayout.setVerticalGroup(
            jPanelPatientDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPatientDiagnosisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(39, 39, 39)
                .addComponent(jPanelPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPatientDiagnosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPatientDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePatientMouseClicked
        int row = jTablePatient.rowAtPoint(evt.getPoint());
        diagnosis_id = jTablePatient.getValueAt(row, 5).toString();
        dataLoadDiagnosis(diagnosis_id);
    }//GEN-LAST:event_jTablePatientMouseClicked

    private void jTableDiagnosisComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableDiagnosisComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDiagnosisComponentAdded

    private void jButtonPatientSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientSearchActionPerformed
        dataLoadPatient(jTextFieldPatientSearch.getText());
    }//GEN-LAST:event_jButtonPatientSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPatientSearch;
    private javax.swing.JLabel jLabelPatientSearch;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelDiagnosis;
    private javax.swing.JPanel jPanelPatient;
    private javax.swing.JPanel jPanelPatientDiagnosis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDiagnosis;
    private javax.swing.JTable jTablePatient;
    private javax.swing.JTextField jTextFieldPatientSearch;
    // End of variables declaration//GEN-END:variables
}
