/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AESViews;

/**
 *
 * @author otamega
 */
public class JInternalFrameViewDiagnosis extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameViewDiagnosis
     */
    public JInternalFrameViewDiagnosis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelViewDiagnosis = new javax.swing.JPanel();
        jLabelViewDiagnosisTitle = new javax.swing.JLabel();
        jPanelOptionFrame = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDiagnosis = new javax.swing.JTable();
        jPanelData = new javax.swing.JPanel();
        jLabelDiagnosisResult = new javax.swing.JLabel();
        jLabelDiagnosisThreatment = new javax.swing.JLabel();
        jTextFieldDiagnosisResult = new javax.swing.JTextField();
        jTextFieldDiagnosisThreatment = new javax.swing.JTextField();
        jLabelDiagnosisId = new javax.swing.JLabel();
        jTextFieldDiagnosisId = new javax.swing.JTextField();
        jButtonReportView = new javax.swing.JButton();

        setTitle("Diagnósticos registrados");

        jLabelViewDiagnosisTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelViewDiagnosisTitle.setText("Diagnósticos registrados");

        jPanelOptionFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Marco de opciones"));

        jButtonSearch.setText("Buscar");

        jButtonEdit.setText("Editar");

        jButtonDelete.setText("Eliminar");

        jButtonRefresh.setText("Refrescar");

        javax.swing.GroupLayout jPanelOptionFrameLayout = new javax.swing.GroupLayout(jPanelOptionFrame);
        jPanelOptionFrame.setLayout(jPanelOptionFrameLayout);
        jPanelOptionFrameLayout.setHorizontalGroup(
            jPanelOptionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jButtonRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDelete)
                .addContainerGap())
        );
        jPanelOptionFrameLayout.setVerticalGroup(
            jPanelOptionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableDiagnosis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDiagnosis);

        jPanelData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabelDiagnosisResult.setText("Resultado:");

        jLabelDiagnosisThreatment.setText("Tratamiento:");

        jLabelDiagnosisId.setText("Código");

        jButtonReportView.setText("Ver reporte");

        javax.swing.GroupLayout jPanelDataLayout = new javax.swing.GroupLayout(jPanelData);
        jPanelData.setLayout(jPanelDataLayout);
        jPanelDataLayout.setHorizontalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDataLayout.createSequentialGroup()
                        .addComponent(jLabelDiagnosisThreatment)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldDiagnosisThreatment)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReportView))
                    .addGroup(jPanelDataLayout.createSequentialGroup()
                        .addComponent(jLabelDiagnosisId)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldDiagnosisId, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDiagnosisResult)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldDiagnosisResult)))
                .addContainerGap())
        );
        jPanelDataLayout.setVerticalGroup(
            jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiagnosisId)
                    .addComponent(jTextFieldDiagnosisId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDiagnosisResult)
                        .addComponent(jTextFieldDiagnosisResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDiagnosisThreatment)
                    .addGroup(jPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDiagnosisThreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReportView)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelViewDiagnosisLayout = new javax.swing.GroupLayout(jPanelViewDiagnosis);
        jPanelViewDiagnosis.setLayout(jPanelViewDiagnosisLayout);
        jPanelViewDiagnosisLayout.setHorizontalGroup(
            jPanelViewDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewDiagnosisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelViewDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOptionFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelViewDiagnosisLayout.createSequentialGroup()
                        .addComponent(jLabelViewDiagnosisTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelViewDiagnosisLayout.setVerticalGroup(
            jPanelViewDiagnosisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewDiagnosisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelViewDiagnosisTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOptionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewDiagnosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonReportView;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelDiagnosisId;
    private javax.swing.JLabel jLabelDiagnosisResult;
    private javax.swing.JLabel jLabelDiagnosisThreatment;
    private javax.swing.JLabel jLabelViewDiagnosisTitle;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JPanel jPanelOptionFrame;
    private javax.swing.JPanel jPanelViewDiagnosis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDiagnosis;
    private javax.swing.JTextField jTextFieldDiagnosisId;
    private javax.swing.JTextField jTextFieldDiagnosisResult;
    private javax.swing.JTextField jTextFieldDiagnosisThreatment;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
